### ISSUE TITLE
Not understandable names

### ISSUE THREAD

**Issue by ksuchernaya** [ZameAlex/CoinsDiffusion#1]
Maybe it'll be better to use "countryName" in case you have used "Name" in different parts which relates both to City and Country

https://github.com/ZameAlex/CoinsDiffusion/blob/c2510efddb11195126b5c0f2fa4c05bfc0571436/Coin_Diffusion/Program.cs#L15

**Comment by ZameAlex** [comment]
But those names are defined in different contexts. We can`t use property Name in class Country separately from object of Country as well as we can`t use property Name in class City separately from object of City. If context are different, it`ll reduce readability.

**Comment by ksuchernaya** [comment]
Ok, I understand your explanation. But first time I have watched code it was not clear.
