### ISSUE TITLE
If else block

### ISSUE THREAD

**Issue by ksuchernaya** [ZameAlex/CoinsDiffusion#2]
Don't you have ideas how to simplify this block?

https://github.com/ZameAlex/CoinsDiffusion/blob/c2510efddb11195126b5c0f2fa4c05bfc0571436/Coin_Diffusion/Program.cs#L20-L33

**Comment by ZameAlex** [comment]
Actually, I have no ideas about it. Maybe, you can advise something to simplify this block?

**Comment by ksuchernaya** [comment]
Any ideas, so I agree with you.
