### ISSUE TITLE
Check for valid parameters

### ISSUE THREAD

**Issue by ksuchernaya** [ZameAlex/CoinsDiffusion#3]
Add verification for different groups of input data: correct, incorrect and empty.
Give some relevant exceptions for users.

https://github.com/ZameAlex/CoinsDiffusion/blob/c2510efddb11195126b5c0f2fa4c05bfc0571436/Coin_Diffusion/Program.cs#L49

**Comment by ZameAlex** [comment]
Yes, I missed cases of incorrect input. I`ll fixed it immediately.

**Comment by ZameAlex** [comment]
Bug was fixed.
