### ISSUE TITLE
Magic number

### ISSUE THREAD

**Issue by ksuchernaya** [ZameAlex/CoinsDiffusion#4]
Don't you want to make this number as a constant?

https://github.com/ZameAlex/CoinsDiffusion/blob/c2510efddb11195126b5c0f2fa4c05bfc0571436/Coin_Diffusion/Transition.cs#L48

**Comment by ZameAlex** [comment]
If we had such value in different parts of system, it`d be reasonable. In that case it`s better to use constant. But in current example it`ll reduce readability, in my opinion. Besides, it saves memory.

**Comment by ksuchernaya** [comment]
Ok. But if you'll want to change this parameter, you should find it in your code.
We have not a big project, so it will not be uncomfortable.
